version: '3.8'

services:
  db:
    image: postgres:13
    container_name: iha_kiralama_db
    environment:
      POSTGRES_DB: new_iha_kiralama_db
      POSTGRES_USER: new_django_user
      POSTGRES_PASSWORD: new_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
