# Generated by Django 5.0.7 on 2024-07-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('seller', 'Seller')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
