# Generated by Django 5.0.7 on 2024-07-17 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_uav_rentalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='uavs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
