# Generated by Django 5.0.7 on 2024-07-17 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_uav_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAVListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_listed', models.BooleanField(default=False)),
                ('uav', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='accounts.uav')),
            ],
        ),
    ]
