# Generated by Django 5.0.7 on 2024-07-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_uavlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uavlisting',
            name='is_listed',
        ),
    ]
