# Generated by Django 3.2.25 on 2024-07-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_uavlisting_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
